In [17]:
from sklearn.tree import DecisionTreeRegressor
import numpy as np 
from sklearn.linear_model import LinearRegression
from numpy.linalg import inv

In [3]:
X = np.random.normal(loc =0, scale =1, size=(100,10))
y = np.random.normal(loc =0, scale =1, size=(100,))

In [66]:
########
# Estimating S 
########
# True y values for 10 datasets
y_true = np.zeros(shape = (10,100))
#print(y_true[0,].shape)
# predicted values for 10 datasets
y_predict = np.zeros(shape = (10,100))
X = np.random.normal(loc =0, scale =1, size=(100,10))
for i in range (10):
    y_rand = np.random.normal(loc = 0, scale = 1, size=(100,))
    y_true[i,] = y_rand
    clf = DecisionTreeRegressor(max_leaf_nodes=3)
    clf.fit(X,y_rand)
    treeObj = clf.tree_
    print (treeObj.node_count)
    y_predict[i,] = clf.predict(X)
    y_predict[i,] = np.mean(y_rand)

print(y_predict[:,0].shape)
S_hat = np.zeros(shape=(100,100))
# Step 2 
for i in range(100):
    #lr = LinearRegression(fit_intercept=False)
    #lr.fit(y_true,y_predict[:,i])
    #S_hat[i,] = lr.coef_
    #print(lr.coef_[:10])
    self_cov = np.dot(np.transpose(y_true),y_true)
    projection_matrix = np.dot(inv(self_cov),np.transpose(y_true))
    params = np.dot(projection_matrix,y_predict[:,i])
    #np.dot(np.dot(inv(np.dot(np.transpose(y_true),y_true)),np.transpose(y_true)),y_predict[:,i])
    S_hat[i,] = params
    #print(params[:10])
    #print(np.dot(np.dot(inv(np.dot(np.transpose(y_true),y_true)),np.transpose(y_true)),y_predict[:,i])[:10])
print(S_hat.shape)
print(np.trace(S_hat))
    
    
    
    

5
5
5
5
5
5
5
5
5
5
(10,)
(100, 100)
3.957943427441796


In [13]:
# leaf node = 1
y_predict = np.zeros(shape=(100,10))
y_true = np.zeros(shape=(100,10))
for i in range(10):
    # generate new values y 
    y = np.random.normal(loc =0, scale =1, size=(100,))
    # leaf node = 1 , then for every point , just equal to average of all 100 y values
    prediction = np.mean(y)
    y_predict[:,i] = prediction
    y_true[:,i] = y

sums = 0
for i in range (100):
    y_1 = y_predict[i,:]
    y_2 = y_true[i,:]
    E1 = np.mean(y_1)
    E2 = np.mean(y_2)
    count = 0
    for j in range (10):
        count += (y_1[j] - E1)*(y_2[j] - E2)
    sums += count
print(sums)    
    

3.6161333483426032


In [8]:
# leaf node = 5,10
y_hat = np.zeros(shape = (100,10))
y_true = np.zeros(shape = (100,10))
for i in range(10):
    # generate new response
    y = np.random.normal(loc =0, scale =1, size=(100,))
    clf = DecisionTreeRegressor(max_leaf_nodes=6)
    clf.fit(X,y)
    treeObj = clf.tree_
    print (treeObj.node_count)
    for j in range(100):
        y_predict = clf.predict(X[j,].reshape(1,-1))
        y_hat[j,i] = y_predict[0]
        y_true[j,i]= y[j]


sums = 0
for i in range(100):
    Ex = np.mean(y_hat[i,])
    Ey = np.mean(y_true[i,])
    for j in range (10):
        #print(y_hat[0,i])
        count += (y_hat[i,j] - Ex)*(y_true[i,j] -Ey)
    sums += count/10
    #print(count)
    count = 0.0
print(sums)

11
11
11
11
11
11
11
11
11
11
33.018839706935296


In [99]:
print(y_hat.shape)
print(y_true.shape)

(100, 10)
(100, 10)


In [101]:
print(y_hat[0,].shape)

(10,)


In [79]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [124]:
tmp = np.stack((y_hat[0,],y_true[0,]),axis = 0)
print(tmp.shape)
print(np.cov(tmp))
print(np.trace(np.cov(tmp)))

Ex = np.mean(y_hat[0,])
Ey = np.mean(y_true[0,])
count = 0.0
print(y_hat[0,0])
print(y_true.shape)
for i in range (10):
    #print(y_hat[0,i])
    count += (y_hat[0,i] - Ex)*(y_true[0,i] -Ey)
print(count/10)
    


(2, 10)
[[ 0.05699503 -0.02494549]
 [-0.02494549  0.89925291]]
0.9562479452301587
-0.01453535031461337
(100, 10)
-0.022450944498543263


In [142]:
a = np.random.normal(loc =0, scale =1, size=(10,1))
b = np.random.normal(loc =0, scale =1, size=(10,1))
print(a)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[-1.3704619 ]
 [ 0.7630314 ]
 [-0.02186064]
 [-0.72814391]
 [ 1.1211619 ]
 [-0.53051406]
 [ 1.04306788]
 [-0.22732768]
 [-0.1595706 ]
 [-1.24267353]]
[[ 1.60200957]
 [-0.22172606]
 [-1.61170325]
 [-0.2672082 ]
 [ 0.03816269]
 [ 0.55381256]
 [ 0.61399367]
 [ 0.07257177]
 [ 0.72751122]
 [-0.21164823]]
[[-1.3704619   1.60200957]
 [ 0.7630314  -0.22172606]
 [-0.02186064 -1.61170325]
 [-0.72814391 -0.2672082 ]
 [ 1.1211619   0.03816269]
 [-0.53051406  0.55381256]
 [ 1.04306788  0.61399367]
 [-0.22732768  0.07257177]
 [-0.1595706   0.72751122]
 [-1.24267353 -0.21164823]]
[[-1.3704619 ]
 [ 0.7630314 ]
 [-0.02186064]
 [-0.72814391]
 [ 1.1211619 ]
 [-0.53051406]
 [ 1.04306788]
 [-0.22732768]
 [-0.1595706 ]
 [-1.24267353]
 [ 1.60200957]
 [-0.22172606]
 [-1.61170325]
 [-0.2672082 ]
 [ 0.03816269]
 [ 0.55381256]
 [ 0.61399367]
 [ 0.07257177]
 [ 0.72751122]
 [-0.21164823]]


In [144]:
a = np.zeros(shape=(100,10))
a[:,0] = 1
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0.